version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: survey-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=<YOUR_DB_HOST>
      - DB_USER=<YOUR_DB_USER>
      - DB_PASSWORD=<YOUR_DB_PASSWORD>
      - DB_NAME=<YOUR_DB_NAME>
      - JWT_SECRET=<YOUR_JWT_SECRET>
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    container_name: survey-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend

  db:
    image: mysql:8.0
    container_name: survey-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: <YOUR_ROOT_PASSWORD>
      MYSQL_DATABASE: <YOUR_DB_NAME>
      MYSQL_USER: <YOUR_DB_USER>
      MYSQL_PASSWORD: <YOUR_DB_PASSWORD>
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data: 